version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build-and-run-test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Run tests
          command: go test -v
  build-docker-image:
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin registry.hub.docker.com
            docker build -t registry.hub.docker.com/rizulhanif/golang:latest .
            docker push registry.hub.docker.com/rizulhanif/golang:latest
workflows:
  test-and-deploy:
    jobs:
      - build-and-run-test
      - build-docker-image:
          requires:
            - build-and-run-test
